name: suitability
channels:
  - conda-forge
dependencies:
  - python=3.*
  - ipython=7.10.*
  - jupyterlab=3.*
  - numpy
  - pandas
  - shapely
  - geopandas
  - matplotlib
  - seaborn
  - folium
  - networkx
  - osmnx
